### ISSUE TITLE
знайдені проблеми

### ISSUE THREAD

**Issue by ipiwebtech** [sevenfox148/WEB#1]
https://sevenfox148.github.io/WEB/lab_1/high_tracks.html
- тут є горизонтальна смуга прокрутки - треба без неї
<img width="954" alt="scroll" src="https://github.com/sevenfox148/WEB/assets/129291207/1b6cb4f6-cea1-48d2-9532-cc3e50f92713">
схоже, ця прокрутка є на всіх сторінках

**Comment by ipiwebtech** [comment]
не знайшов використання тега <map>

**Comment by ipiwebtech** [comment]
<img width="271" alt="eq-margins" src="https://github.com/sevenfox148/WEB/assets/129291207/740e459d-7254-485e-b64b-feeb0a9b4e53">
блок в шапці справа повинен мати однакові відступи зверху і знизу

**Comment by ipiwebtech** [comment]
28.09

блок 3 повзе по висоті, якщо зліва багато тексту
<img width="953" alt="overtexting" src="https://github.com/sevenfox148/WEB/assets/129291207/f9178772-17ee-4c90-b9be-3d67cd95c734">

**Comment by ipiwebtech** [comment]
5.10 продовжуємо
<img width="953" alt="ліва-колонка" src="https://github.com/sevenfox148/WEB/assets/129291207/e59c7bf0-7401-4017-abcd-0446256afd85">

**Comment by sevenfox148** [comment]
Перепрошую, та структура сторінки не передбачає текст в цьому блоці. Для зручності я зробила Вам схему блоків для контенту та блоків для підтримання структури сторінки. Також додала коментарі в коді для позначення блоків, що містять лише інші блоки

![Структура сайту](https://github.com/sevenfox148/WEB/assets/64704817/dfaaca3b-d6d6-4e4d-8b01-2c0a040a4e40)

**Comment by ipiwebtech** [comment]
згоден, не туди вставив текст, перепрошую

тоді недоліків більше не бачу, закриваємо
